defaults: &defaults
  working_directory: ~/currency-flags
  docker:
    - image: circleci/node:10.16

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  publish:
    <<: *defaults
    steps:
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish on npm
          command: npm publish --access=public
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            npm run release-to-github
workflows:
  version: 2
  dependencies-test-and-release:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - publish:
          context: frontend-publish
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          context: frontend-publish
          requires:
            - publish
          filters:
            branches:
              only: master